#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -l walltime=24:00:00 
#PBS -q short 
#PBS -j oe 
#PBS -o /home/vitor/data-analysis/log/$PBS_JOBID.log

cd $PBS_O_WORKDIR

mkdir -p ./log

QTLtools=/home/vitor/Libraries/qtltools/bin/QTLtools
VCF=/home/vitor/data-analysis/data/ALL.chr21_GRCh38.genotypes.20170504.vcf.gz

$QTLtools pca --vcf $VCF --maf 0.05 --distance 6000 --center --scale --out 1000g

